FROM golang:alpine AS build
WORKDIR /illuminatingdeposits
COPY go.mod .
RUN go mod download
COPY internal/ ./internal/
WORKDIR /illuminatingdeposits/cmd/deltacli
COPY cmd/deltacli .
RUN go build

FROM alpine
RUN apk update
RUN apk add bash
WORKDIR /cmd
COPY --from=build /illuminatingdeposits/cmd/deltacli/deltacli .
COPY --from=build /illuminatingdeposits/cmd/deltacli/data/sampleinvest.json ./data/
ENTRYPOINT ["./deltacli", "createInterest"]
CMD ["./data/sampleinvest.json"]